env:
  DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.0'
  HOME: '/build'

steps:
  - label: 'ENV'
    command: 'env'

  - label: 'dependencies'
    command: 'HOME=/build YARN_CACHE_FOLDER=/cache yarn'
    
  - label: 'tests'
    command: 'HOME=/build YARN_CACHE_FOLDER=/cache cd app && yarn test'
