steps:
  - label: 'Unit tests'
    env:
      DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.1'
    agents:
      production: "true"
      platform: "linux"
    commands:
      - 'export HOME=/cache'
      - 'export YARN_CACHE_FOLDER=/cache'
      - 'cd app'
      - 'yarn'
      - 'yarn test'

  - label: 'Integration tests'
    env:
      TERM: "xterm" # colorful output
      DOCKER_IMAGE: 'gcr.io/opensourcecoin/cypress-included:3.2.0'
    agents:
      production: "true"
      platform: "linux"
    commands: '.buildkite/integration.sh'
