steps:
  - label: "Test and package app on Linux"
    command: ".buildkite/run.sh"
    agents:
      production: "true"
      platform: "linux"
    timeout_in_minutes: 60
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-upstream:0.2.2"
      SHARED_MASTER_CACHE: true
    artifact_paths:
      - "dist/*.AppImage"
      - "dist/*.snap"
      - "cypress/screenshots/**/*.png"

  - label: "Test and package app on macOS"
    if: build.branch == 'master'
    command: ".buildkite/run.sh"
    agents:
      production: "false"
      platform: "macos"
    timeout_in_minutes: 60
    artifact_paths:
      - "dist/*.dmg"
      - "cypress/screenshots/**/*.png"
