env:
  DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.0'
  HOME: '/build'

steps:
  - commands:
    - 'env'
    - 'cd app && HOME=/build YARN_CACHE_FOLDER=/cache yarn'
    - 'cd app && HOME=/build YARN_CACHE_FOLDER=/cache yarn test'
