steps:
  - label: 'Integration tests'
    env:
      DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.2'
    agents:
      production: "true"
      platform: "linux"
    command: '.buildkite/integration-tests.sh'
