steps:
  - label: 'Unit tests'
    env:
      DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.1'
    agents:
      production: "true"
      platform: "linux"
    command: '.buildkite/unit.sh'

  - label: 'Integration tests'
    env:
      DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.1'
    agents:
      production: "true"
      platform: "linux"
    command: 'exit 1'
