.test_linux: &test_linux
  label: 'Test and package app on Linux'
  agents:
    production: "true"
    platform: "linux"
  timeout_in_minutes: 60
  env:
    DOCKER_IMAGE: 'gcr.io/opensourcecoin/radicle-upstream:0.2.1'
    SHARED_MASTER_CACHE: true
  command: '.buildkite/run.sh'
  artifact_paths:
    - "app/dist/*.AppImage"
    - "app/dist/*.snap"
    - "app/cypress/screenshots/**/*.png"

.test_macos: &test_macos
  label: 'Test and package app on macOS'
  agents:
    production: "false"
    platform: "macos"
  timeout_in_minutes: 60
  command: '.buildkite/run.sh'
  artifact_paths:
    - "app/dist/*.dmg"
    - "app/cypress/screenshots/**/*.png"

steps:
  - branches: master
    concurrency: 1
    concurrency_group: master
    <<: *test_linux
    <<: *test_macos
  - branches: "!master"
    <<: *test_linux
