env:
  DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.0'
  HOME: '/build'

steps:
  - commands:
    - 'export HOME=build'
    - 'export YARN_CACHE_FOLDER=/cache'
    - 'env'
    - 'cd app'
    - 'ls -lah'
    - 'yarn'
    - 'yarn test'
