.test-linux: &test-linux
  label: "Test and package app on Linux"
  command: "ci/run.sh"
  agents:
    production: "true"
    platform: "linux"
  timeout_in_minutes: 60
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-upstream:0.8.0"
    SHARED_MASTER_CACHE: true
  artifact_paths:
    - "dist/*.AppImage"
    - "cypress/screenshots/**/*.png"
    - "cypress/workspace/test-tmp/*/node-*/*.log"
    - "cypress/workspace/test-tmp/*/combined-node.log"

steps:
  - label: "Test and package app on macOS"
    command: "ci/run.sh"
    agents:
      production: "false"
      platform: "macos"
    timeout_in_minutes: 60
    artifact_paths:
      - "dist/*.dmg"
      - "cypress/screenshots/**/*.png"
      - "cypress/workspace/test-tmp/*/node-*/*.log"
      - "cypress/workspace/test-tmp/*/combined-node.log"
