[package]
name = "proxy"
version = "0.1.0"
authors = ["Alexander Simmerl <xla@monadic.xyz>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
futures = "0.1"
juniper = "0.13"
log = "0.4"
pretty_env_logger = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1"
