[package]
name = "proxy"
version = "0.1.0"
authors = ["Alexander Simmerl <xla@monadic.xyz>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hex = "0.4"
juniper = "0.13"
juniper_warp = "0.4"
log = "0.4"
oscoin_client = { git = "https://github.com/oscoin/oscoin-parity-wasm-prototype", branch = "xla/fix-project-api" }
oscoin_ledger =  { git = "https://github.com/oscoin/oscoin-parity-wasm-prototype", branch = "xla/fix-project-api" }
pretty_env_logger = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1"
