[package]
name = "proxy"
version = "0.1.0"
license = "GPL"
authors = ["Alexander Simmerl <xla@monadic.xyz>"]
edition = "2018"
description = "Proxy to serve a specialised HTTP API to the oscoin MVP."
readme = "https://github.com/oscoin/mvp/blob/master/proxy/README.md"
categories = [ "crypto" ]
keywords = [ "oscoin", "proxy" ]
repository = "https://github.com/oscoin/mvp.git"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hex = "0.4"
juniper = "0.13"
juniper_warp = "0.4"
log = "0.4"
pretty_env_logger = "0.3"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1"

[dependencies.radicle_registry_client]
git = "https://github.com/radicle-dev/radicle-registry.git"
rev = "1bcf23d23ec150ef3a45e903ada9702508a442f4"
