[package]
name = "api"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["radicle team <dev@radicle.xyz>"]
edition = "2018"
description = "Proxy to serve Upstream domain."
readme = "https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/README.md"
categories = [ "code-collaboration", "p2p" ]
keywords = [ "radicle", "upstream", "proxy", "git" ]
repository = "git@github.com:radicle-dev/radicle-upstream.git"
default-run = "api"

[dependencies]
anyhow = "1.0"
directories = "2.0"
futures = { version = "0.3", features = [ "compat" ] }
log = "0.4"
nonempty = { version = "0.6", features = [ "serialize" ] }
percent-encoding = "2.1"
pico-args = "0.3"
pretty_env_logger = "0.3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_qs = "0.6"
tempfile = "3.1"
thiserror = "1.0"
tokio = { version = "0.2", features = [ "dns", "macros", "time" ] }
warp = { version = "0.2", default-features = false }

[dependencies.kv]
git = "https://github.com/zshipko/rust-kv.git"
rev = "a98e1ace84b22ceaac276abf796633bd8e735500"
features = [ "json-value" ]

[dependencies.coco]
path = "../coco"

[dependencies.radicle-surf]
version = "0.5.0"
features = ["serialize"]

[dev-dependencies]
bytes = "0.5"
http = "0.2"
pretty_assertions = "0.6"
