[package]
name = "proxy"
version = "0.1.0"
license = "GPL-3.0-only"
authors = ["radicle team <dev@radicle.xyz>"]
edition = "2018"
description = "Proxy to serve a specialised API to the Upstream UI."
readme = "https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/README.md"
categories = [ "crypto", "p2p" ]
keywords = [ "radicle-upstream", "proxy" ]
repository = "git@github.com:radicle-dev/radicle-upstream.git"
default-run = "proxy"

[dependencies]
coco = { path = "../coco" }
core = { path = "../core" }
http = { path = "../http" }
registry = { path = "../registry" }

directories = "2.0"
futures = { version = "0.3", features = [ "compat" ] }
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
nonempty = "0.5"
percent-encoding = "2.1"
parity-scale-codec = "1.3.1"
pico-args = "0.3"
pretty_env_logger = "0.3"
rand = "0.7"
serde_qs = "0.6"
syntect = "4.2"
tokio = { version = "0.2", features = [ "dns", "macros", "time" ] }
url17 = { package = "url", version = "1.7" }
url = "2.1"

[dev-dependencies]
bytes = "0.5"
pretty_assertions = "0.6"
