name: build
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: "gcr.io/opensourcecoin/radicle-upstream:0.13.0"
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          key: build-${{ runner.os }}-yarn-v3-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-${{ runner.os }}-yarn-v3-
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/cargo
            ~/cache/proxy-target
          key: build-${{ runner.os }}-rust-v1-${{ hashFiles('Cargo.lock') }}
      - run: ci/run.sh
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-artifacts
          path: |
            dist/*.AppImage
            cypress/screenshots/**/*.png
            cypress/workspace/test-tmp/*/node-*/*.log
            cypress/workspace/test-tmp/*/combined-node.log
